# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1e9a9f82-2ff9-431c-b164-6a52fcf48ba4";
    fsType = "btrfs";
    options = [ "subvol=@nix-root" "compress=zstd" ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/C6F3-9E68";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/1e9a9f82-2ff9-431c-b164-6a52fcf48ba4";
    fsType = "btrfs";
    options = [ "subvol=@nix-home" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1e9a9f82-2ff9-431c-b164-6a52fcf48ba4";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd"];
  };
 fileSystems."/home/leesum/workhome" = {
    device = "/dev/disk/by-uuid/1e9a9f82-2ff9-431c-b164-6a52fcf48ba4";
    fsType = "btrfs";
    options = [ "subvol=@workhome" "compress=zstd"];
  };


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2u2u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
